<MainWindow>
    id: main_win
    ScreenManager:
        id: scren_mngr_main
        Screen:
            id: scrn_si
            name: 'scrn_si'         

        Screen:
            id: scrn_li_re
            name: 'scrn_li_re'
        
        Screen:
            id: scrn_li_msg
            name: 'scrn_li_msg'

        Screen:
            id: scrn_send_mail
            name: 'scrn_send_mail'